name: CI

on:
  push:
    branches:
      - main && dev
  pull_request:
    branches:
      - main && dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check code
        run: echo "Good morning Francis"
        shell: bash

  test:
    runs-on: ubuntu-latest
    steps:
      - name: test pipeline
        run: echo "Hello word"
        shell: bash


